server:
  port: 80

spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm550871
    password: 310303
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true

